- id: 200
  key: satoshi
  currency: btc
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0010
  type: WithdrawChannelSatoshi
- id: 300
  key: litecoin
  currency: ltc
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0020
  type: WithdrawChannelLitecoin
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0050
  type: WithdrawChannelEthereum
- id: 800
  key: bitcoincash
  currency: bch
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 2.0000
  type: WithdrawChannelBitcoincash
- id: 900
  key: dashcoin
  currency: dash
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.002
  type: WithdrawChannelDashcoin
- id: 600
  key: ripple
  currency: xrp
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 5.0000
  type: WithdrawChannelRipple
